//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserControls
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class All_Phone_UserControlEntities : DbContext
    {
        public All_Phone_UserControlEntities()
            : base("name=All_Phone_UserControlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Specification> Specifications { get; set; }
    
        public virtual ObjectResult<Get_All_Specs_Result> Get_All_Specs(string mODEL)
        {
            var mODELParameter = mODEL != null ?
                new ObjectParameter("MODEL", mODEL) :
                new ObjectParameter("MODEL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_All_Specs_Result>("Get_All_Specs", mODELParameter);
        }
    }
}
