//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserControls
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specification
    {
        public int Id { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Ram { get; set; }
        public string Storage { get; set; }
        public Nullable<int> Camera { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
